<a href="https://colab.research.google.com/github/paridaabhishek/Alpacatrade/blob/master/AlpecaRestTimeCompare.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install alpaca_trade_api 

     |████████████████████████████████| 45 kB 1.2 MB/s 
     |████████████████████████████████| 1.3 MB 9.7 MB/s 
     |████████████████████████████████| 273 kB 37.2 MB/s 
     |████████████████████████████████| 636 kB 38.8 MB/s 
     |████████████████████████████████| 103 kB 11.8 MB/s 
     |████████████████████████████████| 53 kB 1.0 MB/s 
     |████████████████████████████████| 271 kB 36.3 MB/s 
     |████████████████████████████████| 94 kB 2.6 MB/s 
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Attempting uninstall: msgpack
    Found existing installation: msgpack 1.0.3
    Uninstalling msgpack-1.0.3:
      Successfully uninstalled msgpack-1.0.3


In [2]:
import alpaca_trade_api as tradeapi
api = tradeapi.REST(key_id='PKENE1R5LIQR1J3778D0',secret_key='nT8XMPHULWGvTu4jnDJc6UMK2tSyUAc2YS7npTNV',base_url='https://paper-api.alpaca.markets')





In [3]:
api.get_account()

Account({   'account_blocked': False,
    'account_number': 'PA3WFYAGY0TD',
    'accrued_fees': '0',
    'buying_power': '388187.76',
    'cash': '90642.17',
    'created_at': '2022-02-04T18:16:52.455679Z',
    'crypto_status': 'ACTIVE',
    'currency': 'USD',
    'daytrade_count': 0,
    'daytrading_buying_power': '388187.76',
    'equity': '99750.2',
    'id': '818445eb-79e9-4861-86b3-ce3418a541cc',
    'initial_margin': '4554.015',
    'last_equity': '99791.84',
    'last_maintenance_margin': '2744.9',
    'long_market_value': '9108.03',
    'maintenance_margin': '2732.409',
    'multiplier': '4',
    'non_marginable_buying_power': '90642.17',
    'pattern_day_trader': True,
    'pending_transfer_in': '0',
    'portfolio_value': '99750.2',
    'regt_buying_power': '190392.37',
    'short_market_value': '0',
    'shorting_enabled': True,
    'sma': '99877.15',
    'status': 'ACTIVE',
    'trade_suspended_by_user': False,
    'trading_blocked': False,
    'transfers_blocked': False})

In [15]:
import pandas as pd
import datetime as dtm

In [26]:
end_dt = dtm.date.today()
start_dt = dtm.date.today()


In [29]:
caln = api.get_calendar(start=start_dt,end=end_dt) 

In [43]:
caln[0]

Calendar({   'close': '16:00',
    'date': '2022-02-22',
    'open': '09:30',
    'session_close': '1900',
    'session_open': '0700'})

In [66]:
open.hour


9

In [46]:
date=caln[0].date
open=caln[0].open
close=caln[0].close

In [58]:
date.year


22

In [62]:
date.date()

datetime.date(2022, 2, 22)

In [59]:
date.month


2

In [60]:
date.day

22

In [78]:
trading_start=dtm.datetime.combine(dtm.date(date.year, date.month, date.day), 
                          dtm.time(open.hour, open.minute))+dtm.timedelta(hours=-1)

trading_end=dtm.datetime.combine(dtm.date(date.year, date.month, date.day), 
                          dtm.time(close.hour, close.minute))+dtm.timedelta(hours=-1)


#cst_start = dtm.timedelta(hours=-1)

In [80]:
trading_end
 


datetime.datetime(2022, 2, 22, 16, 0)

In [74]:
trading_start
trading_end

datetime.datetime(2022, 2, 22, 16, 0)

In [82]:
dtm.datetime.now() > trading_start and dtm.datetime.now() < trading_end

False

In [56]:
dtm.datetime.combine(dtm.(date), 
                          dtm.time(open))

AttributeError: ignored

In [7]:
dt=api.get_calendar()

In [13]:
calnDf = pd.DataFrame({                          
         'close': [x.close for x in dt],
         'date': [x.date for x in dt],
         'open': [x.open for x in dt],
         'session_close': [x.session_close for x in dt],
         'session_open': [x.session_open for x in dt]
        })


In [14]:
calnDf

close       date      open session_close session_open
0      16:00:00 1970-01-02  09:30:00      19:00:00     07:00:00
1      16:00:00 1970-01-05  09:30:00      19:00:00     07:00:00
2      16:00:00 1970-01-06  09:30:00      19:00:00     07:00:00
3      16:00:00 1970-01-07  09:30:00      19:00:00     07:00:00
4      16:00:00 1970-01-08  09:30:00      19:00:00     07:00:00
...         ...        ...       ...           ...          ...
15131  16:00:00 2029-12-18  09:30:00      19:00:00     07:00:00
15132  16:00:00 2029-12-19  09:30:00      19:00:00     07:00:00
15133  16:00:00 2029-12-20  09:30:00      19:00:00     07:00:00
15134  16:00:00 2029-12-21  09:30:00      19:00:00     07:00:00
15135  13:00:00 2029-12-24  09:30:00      16:00:00     07:00:00

[15136 rows x 5 columns]

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(10)

array([0.7769583 , 0.76401845, 0.70957129, 0.10726196, 0.0141721 ,
       0.26853293, 0.2795839 , 0.40522289, 0.49016273, 0.18962379])

In [ ]:
np.random.randn(50)

array([-0.09588914, -0.83222519, -1.11357995,  0.7960263 , -0.7905647 ,
        0.25179145,  2.34596541, -0.17432311, -0.91715284,  0.10188473,
       -2.4669826 ,  1.71173138, -2.47902608, -0.78274881, -0.35257278,
        0.45616263, -0.44971948, -0.01193945, -0.62324127, -0.51220941,
       -0.49487736, -0.05290256,  1.90932111,  1.18680864, -0.18943679,
       -1.26682238, -0.58231244, -1.78710072, -0.0716846 ,  1.73547735,
       -1.34546946,  0.40809281, -1.24894967, -0.3244365 ,  0.26897454,
        0.16854412, -0.39701843, -0.14039628, -0.31517029,  1.16753407,
       -0.82466727,  0.03452036, -0.61053289,  0.61674371, -0.18481187,
       -0.63120041, -0.1985555 , -0.81717563,  1.15773289,  1.33764105])

In [ ]:
np.random.randint(1,100)

28

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([ 2, 37, 41, 20, 17, 43, 36, 19, 43, 14])

In [ ]:
import pandas as pd


In [ ]:
labels = ['a','b','c']
mylist = [10,20 ,30]
arr= np.array([10,20,30])
d= {'a':10,'b':20,'c':30}

In [ ]:
pd.Series(data=mylist,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series([sum,max])

0    <built-in function sum>
1    <built-in function max>
dtype: object

In [ ]:
df=pd.DataFrame(np.random.randn(5,4), ['A','B','C','D','E'],['W','X','Y','Z'])

In [ ]:
df['W']

A   -0.150592
B   -0.258555
C    0.043545
D   -1.444995
E    2.846797
Name: W, dtype: float64

In [ ]:
type(df['W'])

pandas.core.series.Series

In [ ]:
df[['W','Z']]

W         Z
A -0.150592  0.398707
B -0.258555 -0.841260
C  0.043545 -1.085732
D -1.444995 -1.610203
E  2.846797 -0.096496

In [ ]:
df>0

W      X      Y      Z
A  False  False  False   True
B  False  False  False  False
C   True   True  False  False
D  False   True  False  False
E   True  False  False  False

In [ ]:
df[df>0]

W        X   Y         Z
A       NaN      NaN NaN  0.398707
B       NaN      NaN NaN       NaN
C  0.043545  2.49599 NaN       NaN
D       NaN  0.35047 NaN       NaN
E  2.846797      NaN NaN       NaN

In [ ]:
df['W']>0

A    False
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [ ]:
df

W         X         Y         Z
A -0.150592 -1.432149 -0.401787  0.398707
B -0.258555 -1.004462 -0.663674 -0.841260
C  0.043545  2.495990 -0.281056 -1.085732
D -1.444995  0.350470 -0.535967 -1.610203
E  2.846797 -0.368896 -0.290677 -0.096496

In [ ]:
df[df['W']>0]

W         X         Y         Z
C  0.043545  2.495990 -0.281056 -1.085732
E  2.846797 -0.368896 -0.290677 -0.096496

In [ ]:
df[df['Z'] < 0][['W','X']].loc[['B','C']]

W         X
B -0.258555 -1.004462
C  0.043545  2.495990