<a href="https://colab.research.google.com/github/paridaabhishek/Alpacatrade/blob/master/AlpecaRest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install alpaca_trade_api 

     |████████████████████████████████| 52 kB 1.5 MB/s 
     |████████████████████████████████| 636 kB 11.7 MB/s 
     |████████████████████████████████| 1.3 MB 44.1 MB/s 
     |████████████████████████████████| 103 kB 48.6 MB/s 
     |████████████████████████████████| 271 kB 74.5 MB/s 
     |████████████████████████████████| 160 kB 63.6 MB/s 
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
import alpaca_trade_api as tradeapi
api = tradeapi.REST(key_id='PKK54IGJ1L4082S92URQ',secret_key='bWTNduAPhmIWhjeMtW7vFx9DIgRZfMNsAB7beGil',base_url='https://paper-api.alpaca.markets')



In [ ]:
api.get_account()

Account({   'account_blocked': False,
    'account_number': 'PA32IDI35I44',
    'accrued_fees': '0',
    'buying_power': '200000',
    'cash': '100000',
    'created_at': '2021-11-03T07:20:09.542934Z',
    'currency': 'USD',
    'daytrade_count': 0,
    'daytrading_buying_power': '0',
    'equity': '100000',
    'id': 'a6085b16-8f08-4eae-afe8-515b50ba56f5',
    'initial_margin': '0',
    'last_equity': '100000',
    'last_maintenance_margin': '0',
    'long_market_value': '0',
    'maintenance_margin': '0',
    'multiplier': '2',
    'non_marginable_buying_power': '100000',
    'pattern_day_trader': False,
    'pending_transfer_in': '0',
    'portfolio_value': '100000',
    'regt_buying_power': '200000',
    'short_market_value': '0',
    'shorting_enabled': True,
    'sma': '0',
    'status': 'ACTIVE',
    'trade_suspended_by_user': False,
    'trading_blocked': False,
    'transfers_blocked': False})

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(10)

array([0.7769583 , 0.76401845, 0.70957129, 0.10726196, 0.0141721 ,
       0.26853293, 0.2795839 , 0.40522289, 0.49016273, 0.18962379])

In [ ]:
np.random.randn(50)

array([-0.09588914, -0.83222519, -1.11357995,  0.7960263 , -0.7905647 ,
        0.25179145,  2.34596541, -0.17432311, -0.91715284,  0.10188473,
       -2.4669826 ,  1.71173138, -2.47902608, -0.78274881, -0.35257278,
        0.45616263, -0.44971948, -0.01193945, -0.62324127, -0.51220941,
       -0.49487736, -0.05290256,  1.90932111,  1.18680864, -0.18943679,
       -1.26682238, -0.58231244, -1.78710072, -0.0716846 ,  1.73547735,
       -1.34546946,  0.40809281, -1.24894967, -0.3244365 ,  0.26897454,
        0.16854412, -0.39701843, -0.14039628, -0.31517029,  1.16753407,
       -0.82466727,  0.03452036, -0.61053289,  0.61674371, -0.18481187,
       -0.63120041, -0.1985555 , -0.81717563,  1.15773289,  1.33764105])

In [ ]:
np.random.randint(1,100)

28

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([ 2, 37, 41, 20, 17, 43, 36, 19, 43, 14])

In [ ]:
import pandas as pd


In [ ]:
labels = ['a','b','c']
mylist = [10,20 ,30]
arr= np.array([10,20,30])
d= {'a':10,'b':20,'c':30}

In [ ]:
pd.Series(data=mylist,index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series([sum,max])

0    <built-in function sum>
1    <built-in function max>
dtype: object

In [ ]:
df=pd.DataFrame(np.random.randn(5,4), ['A','B','C','D','E'],['W','X','Y','Z'])

In [ ]:
df['W']

A   -0.150592
B   -0.258555
C    0.043545
D   -1.444995
E    2.846797
Name: W, dtype: float64

In [ ]:
type(df['W'])

pandas.core.series.Series

In [ ]:
df[['W','Z']]

W         Z
A -0.150592  0.398707
B -0.258555 -0.841260
C  0.043545 -1.085732
D -1.444995 -1.610203
E  2.846797 -0.096496

In [ ]:
df>0

W      X      Y      Z
A  False  False  False   True
B  False  False  False  False
C   True   True  False  False
D  False   True  False  False
E   True  False  False  False

In [ ]:
df[df>0]

W        X   Y         Z
A       NaN      NaN NaN  0.398707
B       NaN      NaN NaN       NaN
C  0.043545  2.49599 NaN       NaN
D       NaN  0.35047 NaN       NaN
E  2.846797      NaN NaN       NaN

In [ ]:
df['W']>0

A    False
B    False
C     True
D    False
E     True
Name: W, dtype: bool

In [ ]:
df

W         X         Y         Z
A -0.150592 -1.432149 -0.401787  0.398707
B -0.258555 -1.004462 -0.663674 -0.841260
C  0.043545  2.495990 -0.281056 -1.085732
D -1.444995  0.350470 -0.535967 -1.610203
E  2.846797 -0.368896 -0.290677 -0.096496

In [ ]:
df[df['W']>0]

W         X         Y         Z
C  0.043545  2.495990 -0.281056 -1.085732
E  2.846797 -0.368896 -0.290677 -0.096496

In [ ]:
df[df['Z'] < 0][['W','X']].loc[['B','C']]

W         X
B -0.258555 -1.004462
C  0.043545  2.495990